services:
  db:
    container_name: mysql
    image: mysql:8.1
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=adm_videos
    security_opt:
      - seccomp:unconfined
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/opt/mysql
    networks:
      - adm_videos_network
volumes:
  mysql_data:

networks:
  adm_videos_network:
