services:
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=juliano
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=fullcycle
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
      - postgres_volume:/var/lib/postgresql/data

volumes:
  postgres_volume:
