CREATE TABLE Clients(
    Id VARCHAR(36) PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Email VARCHAR(255) UNIQUE NOT NULL,
    CreatedAt TIMESTAMP DEFAULT NOW(),
    UpdatedAt TIMESTAMP DEFAULT NOW()
);

CREATE TABLE Accounts(
    Id VARCHAR(36) PRIMARY KEY,
    ClientId VARCHAR(36) NOT NULL,
    Balance DECIMAL(10, 2) DEFAULT 0.00,
    CreatedAt TIMESTAMP DEFAULT NOW(),
    UpdatedAt TIMESTAMP DEFAULT NOW(),
    FOREIGN KEY (ClientId) REFERENCES Clients(Id)
);

CREATE TABLE Transactions(
    Id VARCHAR(36) PRIMARY KEY,
    AccountFromId VARCHAR(36) NOT NULL,
    AccountToId VARCHAR(36) NOT NULL,
    Amount DECIMAL(10, 2) NOT NULL,
    CreatedAt TIMESTAMP DEFAULT NOW()
);
