services:
  db:
    image: mysql
    container_name: db
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 3
    restart: always
    networks:
      - fullcycle
  app:
    build: .
    container_name: app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: always
    networks:
      - fullcycle
  proxy:
    image: nginx
    container_name: proxy
    ports:
      - '8080:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - fullcycle
volumes:
  db_data:

networks:
  fullcycle:
    driver: bridge
