services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.1
    container_name: keycloak
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://db:5432/keycloak
      - KC_DB_USERNAME=juliano
      - KC_DB_PASSWORD=12345678
    ports:
      - 8080:8080
    command: start-dev
    depends_on:
      - db
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=juliano
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=keycloak
    ports:
      - 5432:5432
    restart: always
    volumes:
      - postgres_volume:/var/lib/postgresql/data

volumes:
  postgres_volume:
